<a href="https://colab.research.google.com/github/kledihaxhimali/Data-Science-Projects/blob/Password-Prediction/PredictPassword.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DATA COLLECTION

In [1]:
from sqlite3.dbapi2 import connect
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3
con = sqlite3.connect("password_data.sqlite")
data= pd.read_sql_query("SELECT * FROM Users", con)#return a data frame

In [2]:
data.shape

(100000, 3)

# DATA CLEANING

In [3]:
data.columns

Index(['index', 'password', 'strength'], dtype='object')

In [4]:
data.drop(["index"], axis=1, inplace=True)
data.head(4)

                  password  strength
0                zxe870819         1
1             xw46454nr23l         1
2                soporte13         1
3  accounts6000webhost.com         2

In [5]:
data.duplicated().sum()

np.int64(0)

In [6]:
data.isnull().any()

password    False
strength    False
dtype: bool

In [7]:
data.isnull().any().sum()

np.int64(0)

In [8]:
data.dtypes

password    object
strength     int64
dtype: object

In [9]:
data["strength"].unique()

array([1, 2, 0])

# DATA ANALYSIS

Semantic Analysis

In [10]:
data["password"]

0                      zxe870819
1                   xw46454nr23l
2                      soporte13
3        accounts6000webhost.com
4                       c443balg
                  ...
99995                 obejofi215
99996                 fmiopvxb64
99997                  czvrbun38
99998                  mymyxe430
99999                glqjhkxb467
Name: password, Length: 100000, dtype: object

In [11]:
data["password"][0]
type(data["password"][0])

str

In [12]:
data["password"].str.isnumeric()

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Name: password, Length: 100000, dtype: bool

In [13]:
data[data["password"].str.isnumeric()]

      password  strength
12280   943801         0
14992    12345         0
20958   147856         0
21671   140290         0
23269   123987         0
28569  1233214         0
31329  0159456         0
32574   363761         0
37855  4524344         0
43648  5521597         0
45271   626262         0
52266   156651         0
58717      369         0
59619   151106         0
67723     1234         0
68106  1995151         0
68592   112233         0
69255  9562489         0
74938       12         0
77298    18731         0
86406     1050         0
86608   158491         0
94908   060415         0
96459        1         0
98122  6975818         0
98248   454545         0

In [14]:
data[data["password"].str.isnumeric()].shape

(26, 2)

In [15]:
data[data["password"].str.isupper()].shape

(1506, 2)

In [16]:
data[data["password"].str.isalpha()].shape

(50, 2)

In [17]:
data[data["password"].str.isalnum()].shape

(97203, 2)

In [18]:
data[data["password"].str.istitle()] #first letter capital

                  password  strength
64       Hisanthoshjasika0         2
242    Therockrockbottom72         2
338               1A2S3D4F         1
367              13269123A         1
526        Csicskarozsika1         2
...                    ...       ...
99168          1053815198M         1
99192      Alfranx05122023         2
99375       Kensington1956         2
99590           V13000993J         1
99654       94010Centuripe         2

[932 rows x 2 columns]

In [19]:
import string
string.punctuation

def find_semantics(row):
  for char in row:
    if char in string.punctuation:
      return 1
    else:
      pass
data["password"].apply(find_semantics)==1

0        False
1        False
2        False
3         True
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Name: password, Length: 100000, dtype: bool

In [20]:
data[data["password"].apply(find_semantics)==1]

                      password  strength
3      accounts6000webhost.com         2
68                12463773800+         1
98                  p.r.c.d.g.         1
145                  cita-cita         1
180         karolina.susnina0U         2
...                        ...       ...
99748             maiselis.com         1
99845          hosting4meze!@#         2
99954         semista_bakung15         2
99980         halflife2010!LEB         2
99988                lbhtrnjh@         1

[2663 rows x 2 columns]

# FEATURE ENGINEERING

In [21]:
data["password"][0]

'zxe870819'

In [22]:
len(data["password"][0])

9

In [23]:
data['length'] = data["password"].str.len()

In [24]:
password = 'Shan99'

In [25]:
len([char for char in password if char.islower()])

3

In [26]:
def freq_lowercase(row):
  return len([char for char in row if char.islower()])/len(row)

In [27]:
def freq_uppercase(row):
  return len([char for char in row if char.isupper()])/len(row)

In [28]:
def freq_numerical_case(row):
  return len([char for char in row if char.isdigit()])/len(row)

In [29]:
def freq_special_case(row):
   special_chars= []
   for char in row:
    if not char.isalpha() and not char .isdigit():
      special_chars.append(char)
   return len(special_chars)/len(row)

In [30]:
data["lower_freq"] = np.round(data["password"].apply(freq_lowercase), 3)
data["upper_frew"] = np.round(data["password"].apply(freq_uppercase), 3 )
data["digit_freq"] = np.round(data["password"].apply(freq_numerical_case), 3)
data["special_freq"] = np.round(data["password"].apply(freq_special_case),3)
data.head(4)

,password,strength,length,lower_freq,upper_frew,digit_freq,special_freq
0,zxe870819,1,9,0.333,0.0,0.667,0.000
1,xw46454nr23l,1,12,0.417,0.0,0.583,0.000
2,soporte13,1,9,0.778,0.0,0.222,0.000
3,accounts6000webhost.com,2,23,0.783,0.0,0.174,0.043